### PR TITLE
remove web directory

### PR DESCRIPTION
**Pull request by Remo**

### CODE REVIEW

**Comment by mlocati** [comment]
Thanks Remo! BTW we have to still support concrete5 Legacy... see https://github.com/mlocati/concrete5-translation-tools/commit/d31fce61ae04eb3470b2178f48d861a3f21d5664

**Comment by Remo** [comment]
oh good thing someone is thinking :+1:

**Comment by mlocati** [comment]
Production server updated (see http://yourserver/transifex/core-dev-8.pot :wink: )

**Comment by Remo** [comment]
awesome, thanks

**Pull request closed without merging**
